/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace MatchLibrary {
  export type OrderStruct = {
    status: PromiseOrValue<BigNumberish>;
    trader: PromiseOrValue<string>;
    reward: PromiseOrValue<BigNumberish>;
    amountToSell: PromiseOrValue<BigNumberish>;
    amountToBuy: PromiseOrValue<BigNumberish>;
    amountToSellRest: PromiseOrValue<BigNumberish>;
    amountToBuyRest: PromiseOrValue<BigNumberish>;
  };

  export type OrderStructOutput = [
    number,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    status: number;
    trader: string;
    reward: BigNumber;
    amountToSell: BigNumber;
    amountToBuy: BigNumber;
    amountToSellRest: BigNumber;
    amountToBuyRest: BigNumber;
  };

  export type ActionStruct = {
    actionType: PromiseOrValue<BigNumberish>;
    data: PromiseOrValue<BytesLike>;
  };

  export type ActionStructOutput = [number, string] & {
    actionType: number;
    data: string;
  };
}

export interface MatchContractInterface extends utils.Interface {
  functions: {
    "PRICE_DECIMALS()": FunctionFragment;
    "PRICE_PRECISION()": FunctionFragment;
    "bank()": FunctionFragment;
    "changeBank(address)": FunctionFragment;
    "execute((uint8,bytes)[])": FunctionFragment;
    "minReward()": FunctionFragment;
    "owner()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdraw()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "PRICE_DECIMALS"
      | "PRICE_PRECISION"
      | "bank"
      | "changeBank"
      | "execute"
      | "minReward"
      | "owner"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "PRICE_DECIMALS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PRICE_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bank", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "changeBank",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [MatchLibrary.ActionStruct[]]
  ): string;
  encodeFunctionData(functionFragment: "minReward", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "PRICE_DECIMALS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PRICE_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bank", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "changeBank", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minReward", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "AddOrder(address,address,address,uint256,tuple)": EventFragment;
    "Cancel(address,address,address,uint256,tuple)": EventFragment;
    "Deposit(address,address,uint256,uint256)": EventFragment;
    "Match(address,address,address,address,uint256,uint256,tuple,tuple)": EventFragment;
    "Withdraw(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AddOrder"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Cancel"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Deposit"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Match"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Withdraw"): EventFragment;
}

export interface AddOrderEventObject {
  user: string;
  tokenToSell: string;
  tokenToBuy: string;
  indexOrder: BigNumber;
  order: MatchLibrary.OrderStructOutput;
}
export type AddOrderEvent = TypedEvent<
  [string, string, string, BigNumber, MatchLibrary.OrderStructOutput],
  AddOrderEventObject
>;

export type AddOrderEventFilter = TypedEventFilter<AddOrderEvent>;

export interface CancelEventObject {
  user: string;
  tokenToSell: string;
  tokenToBuy: string;
  indexOrder: BigNumber;
  order: MatchLibrary.OrderStructOutput;
}
export type CancelEvent = TypedEvent<
  [string, string, string, BigNumber, MatchLibrary.OrderStructOutput],
  CancelEventObject
>;

export type CancelEventFilter = TypedEventFilter<CancelEvent>;

export interface DepositEventObject {
  user: string;
  token: string;
  desiredAmount: BigNumber;
  depositedAmount: BigNumber;
}
export type DepositEvent = TypedEvent<
  [string, string, BigNumber, BigNumber],
  DepositEventObject
>;

export type DepositEventFilter = TypedEventFilter<DepositEvent>;

export interface MatchEventObject {
  userA: string;
  tokenToSell: string;
  tokenToBuy: string;
  userB: string;
  indexOrderA: BigNumber;
  indexOrderB: BigNumber;
  orderA: MatchLibrary.OrderStructOutput;
  orderB: MatchLibrary.OrderStructOutput;
}
export type MatchEvent = TypedEvent<
  [
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    MatchLibrary.OrderStructOutput,
    MatchLibrary.OrderStructOutput
  ],
  MatchEventObject
>;

export type MatchEventFilter = TypedEventFilter<MatchEvent>;

export interface WithdrawEventObject {
  user: string;
  to: string;
  amount: BigNumber;
}
export type WithdrawEvent = TypedEvent<
  [string, string, BigNumber],
  WithdrawEventObject
>;

export type WithdrawEventFilter = TypedEventFilter<WithdrawEvent>;

export interface MatchContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MatchContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    PRICE_DECIMALS(overrides?: CallOverrides): Promise<[BigNumber]>;

    PRICE_PRECISION(overrides?: CallOverrides): Promise<[BigNumber]>;

    bank(overrides?: CallOverrides): Promise<[string]>;

    changeBank(
      newBank: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    execute(
      actions: MatchLibrary.ActionStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    minReward(overrides?: CallOverrides): Promise<[BigNumber]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  PRICE_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

  PRICE_PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

  bank(overrides?: CallOverrides): Promise<string>;

  changeBank(
    newBank: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  execute(
    actions: MatchLibrary.ActionStruct[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  minReward(overrides?: CallOverrides): Promise<BigNumber>;

  owner(overrides?: CallOverrides): Promise<string>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    PRICE_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

    PRICE_PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

    bank(overrides?: CallOverrides): Promise<string>;

    changeBank(
      newBank: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    execute(
      actions: MatchLibrary.ActionStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    minReward(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<string>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "AddOrder(address,address,address,uint256,tuple)"(
      user?: PromiseOrValue<string> | null,
      tokenToSell?: PromiseOrValue<string> | null,
      tokenToBuy?: PromiseOrValue<string> | null,
      indexOrder?: null,
      order?: null
    ): AddOrderEventFilter;
    AddOrder(
      user?: PromiseOrValue<string> | null,
      tokenToSell?: PromiseOrValue<string> | null,
      tokenToBuy?: PromiseOrValue<string> | null,
      indexOrder?: null,
      order?: null
    ): AddOrderEventFilter;

    "Cancel(address,address,address,uint256,tuple)"(
      user?: PromiseOrValue<string> | null,
      tokenToSell?: PromiseOrValue<string> | null,
      tokenToBuy?: PromiseOrValue<string> | null,
      indexOrder?: null,
      order?: null
    ): CancelEventFilter;
    Cancel(
      user?: PromiseOrValue<string> | null,
      tokenToSell?: PromiseOrValue<string> | null,
      tokenToBuy?: PromiseOrValue<string> | null,
      indexOrder?: null,
      order?: null
    ): CancelEventFilter;

    "Deposit(address,address,uint256,uint256)"(
      user?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      desiredAmount?: null,
      depositedAmount?: null
    ): DepositEventFilter;
    Deposit(
      user?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      desiredAmount?: null,
      depositedAmount?: null
    ): DepositEventFilter;

    "Match(address,address,address,address,uint256,uint256,tuple,tuple)"(
      userA?: PromiseOrValue<string> | null,
      tokenToSell?: PromiseOrValue<string> | null,
      tokenToBuy?: PromiseOrValue<string> | null,
      userB?: null,
      indexOrderA?: null,
      indexOrderB?: null,
      orderA?: null,
      orderB?: null
    ): MatchEventFilter;
    Match(
      userA?: PromiseOrValue<string> | null,
      tokenToSell?: PromiseOrValue<string> | null,
      tokenToBuy?: PromiseOrValue<string> | null,
      userB?: null,
      indexOrderA?: null,
      indexOrderB?: null,
      orderA?: null,
      orderB?: null
    ): MatchEventFilter;

    "Withdraw(address,address,uint256)"(
      user?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      amount?: null
    ): WithdrawEventFilter;
    Withdraw(
      user?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      amount?: null
    ): WithdrawEventFilter;
  };

  estimateGas: {
    PRICE_DECIMALS(overrides?: CallOverrides): Promise<BigNumber>;

    PRICE_PRECISION(overrides?: CallOverrides): Promise<BigNumber>;

    bank(overrides?: CallOverrides): Promise<BigNumber>;

    changeBank(
      newBank: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    execute(
      actions: MatchLibrary.ActionStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    minReward(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    PRICE_DECIMALS(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PRICE_PRECISION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    bank(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    changeBank(
      newBank: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    execute(
      actions: MatchLibrary.ActionStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    minReward(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
